name = "UnitfulCosmo"
uuid = "961331e1-62bb-46d9-b9e3-f058129f1391"
authors = ["Zack Li"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
